// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import path from 'path';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Check if we're in development and can create a Supabase client
// In production, all operations should go through the API
let supabase: ReturnType<typeof createClient<Database>> | null = null;

if (SUPABASE_URL && SUPABASE_PUBLISHABLE_KEY) {
  supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
    },
  });
} else {
  console.warn('Supabase credentials not found. Frontend will use API for all operations.');
}

// Export a mock client if not available
export const supabaseClient = supabase || {
  auth: { signOut: async () => {} },
  storage: {
    from: () => ({
      upload: async () => ({ error: new Error('Supabase not configured') }),
      download: async () => ({ error: new Error('Supabase not configured') }),
    }),
  },
};

// For backward compatibility, export as 'supabase'
export { supabaseClient as supabase };
